const currencies = [
  {
    code: 'AUD',
    country: 'Australia',
    name: 'Australian dollar',
    symbol: 'AU$',
    emoji: '🇦🇺',
  },
  {
    code: 'CNY',
    country: 'China',
    name: 'Chinese yuan',
    symbol: '¥',
    emoji: '🇨🇳',
  },
  {
    code: 'USD',
    country: 'United States',
    name: 'United States dollar',
    symbol: 'US$',
    emoji: '🇺🇸',
  },
  {
    code: 'GBP',
    country: 'United Kingdom',
    name: 'British pound',
    symbol: '£',
    emoji: '🇬🇧',
  },
  {
    code: 'HKD',
    country: 'Hong Kong',
    name: 'Hong Kong dollar',
    symbol: 'HK$',
    emoji: '🇭🇰',
  },
  {
    code: 'EUR',
    country: 'Eurozone',
    name: 'Euro',
    symbol: '€',
    emoji: '🇪🇺',
  },
  {
    code: 'CAD',
    country: 'Canada',
    name: 'Canadian dollar',
    symbol: 'CA$',
    emoji: '🇨🇦',
  },
  {
    code: 'SGD',
    country: 'Singapore',
    name: 'Singapore dollar',
    symbol: 'SG$',
    emoji: '🇸🇬',
  },
  {
    code: 'CHF',
    country: 'Switzerland',
    name: 'Swiss franc',
    symbol: 'CHf',
    emoji: '🇨🇭',
  },
  {
    code: 'NZD',
    country: 'New Zealand',
    name: 'New Zealand dollar',
    symbol: 'NZ$',
    emoji: '🇳🇿',
  },
  {
    code: 'JPY',
    country: 'Japan',
    name: 'Japanese yen',
    symbol: '¥',
    emoji: '🇯🇵',
  },
  {
    code: 'THB',
    country: 'Thailand',
    name: 'Thai baht',
    symbol: '฿',
    emoji: '🇹🇭',
  },
  {
    code: 'SEK',
    country: 'Sweden',
    name: 'Swedish krona',
    symbol: 'kr',
    emoji: '🇸🇪',
  },
  {
    code: 'NOK',
    country: 'Norway',
    name: 'Norwegian krone',
    symbol: 'kr',
    emoji: '🇳🇴',
  },
  {
    code: 'DKK',
    country: 'Denmark',
    name: 'Danish krone',
    symbol: 'Kr.',
    emoji: '🇩🇰',
  },
  {
    code: 'HUF',
    country: 'Hungary',
    name: 'Hungarian forint',
    symbol: 'Ft',
    emoji: '🇭🇺',
  },
  {
    code: 'CZK',
    country: 'Czech Republic',
    name: 'Czech koruna',
    symbol: 'Kč',
    emoji: '🇨🇿',
  },
  {
    code: 'PLN',
    country: 'Poland',
    name: 'Polish złoty',
    symbol: 'zł',
    emoji: '🇵🇱',
  },
  {
    code: 'RON',
    country: 'Romania',
    name: 'Romanian leu',
    symbol: 'lei',
    emoji: '🇷🇴',
  },
  {
    code: 'IDR',
    country: 'Indonesia',
    name: 'Indonesian rupiah',
    symbol: 'Rp',
    emoji: '🇮🇩',
  },
  {
    code: 'MYR',
    country: 'Malaysian',
    name: 'Malaysian ringgit',
    symbol: 'RM',
    emoji: '🇲🇾',
  },
  {
    code: 'TWD',
    country: 'Taiwan',
    name: 'New Taiwan dollar',
    symbol: 'TW$',
    emoji: '🇹🇼',
  },
  {
    code: 'VND',
    country: 'Vietnam',
    name: 'Vietnamese đồng',
    symbol: '₫',
    emoji: '🇻🇳',
  },
  {
    code: 'KRW',
    country: 'South Korea',
    name: 'Won',
    symbol: '₩',
    emoji: '🇰🇷',
  },
  {
    code: 'MXN',
    country: 'Mexico',
    name: 'Mexican peso',
    symbol: 'MX$',
    emoji: '🇲🇽',
  },
  {
    code: 'ILS',
    country: 'Israel',
    name: 'Israeli new shekel',
    symbol: '₪',
    emoji: '🇮🇱',
  },
  {
    code: 'ZAR',
    country: 'South Africa',
    name: 'South African rand',
    symbol: 'R',
    emoji: '🇿🇦',
  },
  {
    code: 'AED',
    country: 'United Arab Emirates',
    name: 'United Arab Emirates dirham',
    symbol: 'إ.د',
    emoji: '🇦🇪',
  },
];

export default currencies;
